// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repositorio;

#nullable disable

namespace Repositorio.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Dominio.Modelos.Lucro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataLucro")
                        .HasColumnType("DateTime")
                        .HasColumnName("DataLucro");

                    b.Property<short>("MeioPagamentoEnum")
                        .HasColumnType("smallint")
                        .HasColumnName("MeioPagamentoEnum");

                    b.Property<double>("Valor")
                        .HasColumnType("Float")
                        .HasColumnName("Valor");

                    b.Property<int>("VendedorId")
                        .HasColumnType("int")
                        .HasColumnName("VendedorId");

                    b.HasKey("Id");

                    b.HasIndex("VendedorId");

                    b.ToTable("Lucro", (string)null);
                });

            modelBuilder.Entity("Dominio.Modelos.Venda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataVenda")
                        .HasColumnType("DateTime")
                        .HasColumnName("DataVenda");

                    b.Property<short>("MeioPagamentoEnum")
                        .HasColumnType("smallint")
                        .HasColumnName("MeioPagamento");

                    b.Property<short>("Processado")
                        .HasColumnType("smallint")
                        .HasColumnName("Processado");

                    b.Property<double>("Valor")
                        .HasColumnType("Float")
                        .HasColumnName("Valor");

                    b.Property<int>("VendedorId")
                        .HasColumnType("int")
                        .HasColumnName("VendedorId");

                    b.HasKey("Id");

                    b.HasIndex("VendedorId");

                    b.ToTable("Venda", (string)null);
                });

            modelBuilder.Entity("Dominio.Modelos.Vendedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<short>("ClasseVendedorEnum")
                        .HasColumnType("smallint")
                        .HasColumnName("ClassVendedor");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR")
                        .HasColumnName("Email");

                    b.Property<int>("Matricula")
                        .HasMaxLength(8)
                        .HasColumnType("int")
                        .HasColumnName("Matricula");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("NVARCHAR")
                        .HasColumnName("Name");

                    b.Property<short>("Sexo")
                        .HasColumnType("smallint")
                        .HasColumnName("Sexo");

                    b.HasKey("Id");

                    b.ToTable("Vendedor", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 2,
                            ClasseVendedorEnum = (short)1,
                            Email = "vendedor1@dominio.com",
                            Matricula = 12345678,
                            Nome = "Vendedor1",
                            Sexo = (short)0
                        },
                        new
                        {
                            Id = 3,
                            ClasseVendedorEnum = (short)1,
                            Email = "vendedor2@dominio.com",
                            Matricula = 12345678,
                            Nome = "Vendedor2",
                            Sexo = (short)1
                        },
                        new
                        {
                            Id = 4,
                            ClasseVendedorEnum = (short)1,
                            Email = "vendedor3@dominio.com",
                            Matricula = 12345678,
                            Nome = "Vendedor3",
                            Sexo = (short)0
                        },
                        new
                        {
                            Id = 5,
                            ClasseVendedorEnum = (short)2,
                            Email = "vendedor4@dominio.com",
                            Matricula = 12345678,
                            Nome = "Vendedor4",
                            Sexo = (short)1
                        },
                        new
                        {
                            Id = 6,
                            ClasseVendedorEnum = (short)1,
                            Email = "vendedor5@dominio.com",
                            Matricula = 12345678,
                            Nome = "Vendedor5",
                            Sexo = (short)0
                        },
                        new
                        {
                            Id = 7,
                            ClasseVendedorEnum = (short)2,
                            Email = "vendedor6@dominio.com",
                            Matricula = 12345678,
                            Nome = "Vendedor6",
                            Sexo = (short)1
                        },
                        new
                        {
                            Id = 8,
                            ClasseVendedorEnum = (short)1,
                            Email = "vendedor7@dominio.com",
                            Matricula = 12345678,
                            Nome = "Vendedor7",
                            Sexo = (short)0
                        },
                        new
                        {
                            Id = 9,
                            ClasseVendedorEnum = (short)2,
                            Email = "vendedor8@dominio.com",
                            Matricula = 12345678,
                            Nome = "Vendedor8",
                            Sexo = (short)1
                        },
                        new
                        {
                            Id = 10,
                            ClasseVendedorEnum = (short)2,
                            Email = "vendedor9@dominio.com",
                            Matricula = 12345678,
                            Nome = "Vendedor9",
                            Sexo = (short)0
                        },
                        new
                        {
                            Id = 11,
                            ClasseVendedorEnum = (short)2,
                            Email = "vendedor10@dominio.com",
                            Matricula = 12345678,
                            Nome = "Vendedor10",
                            Sexo = (short)1
                        });
                });

            modelBuilder.Entity("Dominio.Modelos.Lucro", b =>
                {
                    b.HasOne("Dominio.Modelos.Vendedor", "Vendedor")
                        .WithMany("Lucros")
                        .HasForeignKey("VendedorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Vendedor");
                });

            modelBuilder.Entity("Dominio.Modelos.Venda", b =>
                {
                    b.HasOne("Dominio.Modelos.Vendedor", "Vendedor")
                        .WithMany("Vendas")
                        .HasForeignKey("VendedorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Vendedor");
                });

            modelBuilder.Entity("Dominio.Modelos.Vendedor", b =>
                {
                    b.Navigation("Lucros");

                    b.Navigation("Vendas");
                });
#pragma warning restore 612, 618
        }
    }
}
